import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import Header from "@/app/Header";
import Footer from "@/app/Footer";
import React from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <body>
      <Header/>
      <main>{children}</main>
      <Footer/>
      </body>
      </html>
  )
}